/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataModel;

import org.json.simple.JSONObject;

/**
 * Represents a word from a sentence.
 * @author @wesleywilly [https://github.com/wesleywilly]
 */
public class Word {
    private static final String VALUE = "value";
    private static final String STANFORD_TAG = "stanford_tag";
    
    private String value;
    private String stanfordTag;
    
    /**
     * Builds the object.
     * @param value = the word itself.
     * @param stanfordTag = Stores tag generated by the stanford parser.
     */
    public Word(String value, String stanfordTag){
        this.value = value;
        this.stanfordTag = stanfordTag;
    }
    
    /**
     * Build the object.
        StanfordTag = null;
     * @param value = the word itself.
     */
    public Word (String value){
        this.value = value;
        this.stanfordTag = "";
    }
    
    /**
     * Constructs the object from a JSONObject.
     * The JSONObject with same data structure can be generated by toJSON method in this class.
     * @param jWord = JSONObject with a similar data structure
     */
    public Word(JSONObject jWord){
        
        if(jWord.containsKey(VALUE)){
            value = (String) jWord.get(VALUE);
        }else{
            value = null;
        }
        
        if(jWord.containsKey(STANFORD_TAG)){
            stanfordTag = (String) jWord.get(STANFORD_TAG);
        }else{
            stanfordTag = null;
        }
    }
    
    /**
     * Returns a JSONObject with a similar data structure of this Object
     * @return JSONObject
     */
    public JSONObject toJSON(){
        JSONObject jWord = new JSONObject();
        if(!value.isEmpty() && value != null){
            jWord.put(VALUE, value);
            if(!stanfordTag.isEmpty() && stanfordTag != null){
                jWord.put(STANFORD_TAG, stanfordTag);
            }
        }
        return jWord;
    }
    
    /**
     * Returns the word value
     */
    public String getValue() {
        return value;
    }
    /**
     * Returns the tag generated by the stanford parser for this word.
     */
    public String getStanfordTag() {
        return stanfordTag;
    }

    /**
     * Set the tag generated by the stanford parser for this word.
     * @param stanfordTag 
     */
    public void setStanfordTag(String stanfordTag) {
        this.stanfordTag = stanfordTag;
    }
    
}
